---
title: "mRNA-full-timedata"
author: "Yajie Guo"
date: "04/09/2024"
output: html_document
extra_dependencies: ['amsmath', 'someotherpackage','extarrows','color','amssymb','cases']
package: 'dplyr','plot3D','rgl'
---


```{r}
# The original stochastic model with three reactions

ssa.f<-function(Mt,theta,S0){
  
  Sini<-S0
  
  names(Sini)<-c('S1','S2')
  
  S.can<-S0
  
  t<-0
  
  Reaction<-matrix(c(-1,0,0,+1,0,-1),byrow=TRUE,ncol=2)
  
  while(t[length(t)] <= Mt){
    
    if ( S.can[1] != 0  |   S.can[2] != 0 ){
      
      theta.can<-c(theta[1]*S.can[1], theta[2]*S.can[1], theta[3]*S.can[2])
      
      lambda<-sum(theta.can, na.rm = T) 
      
      wait<-rexp(1,rate=lambda)
      
      
      t[length(t)+1] <-t[length(t)]+wait
      
      if ( S.can[1] > 0  ){
        
        
        prob<-theta.can/lambda   
        
        R.can<-sample(size =1,x=c(1,2,3), prob = prob)
        
        
        
        if(R.can==1){
          S.can<-S.can+Reaction[1,] } else{
            
            if(R.can==3){
              S.can<-S.can+Reaction[3,]
            }else{
              
              S.can<-S.can+Reaction[2,]
            }
          }
        
      }else{
        
        if(S.can[2] > 0){
          S.can<- S.can+Reaction[3,] }else{ return( cbind.data.frame(t,Sini) )  } 
        
      }
      
    }else{ return(cbind.data.frame(t,Sini) )}
    
    Sini<-rbind.data.frame(Sini,S.can)
    
  }
  
  
names(Sini)<-paste0('Species',c('mRNA','Protein'))
 cbind.data.frame(jump.times=t,Sini)

}



```



##########################################################################
# the iteration of original stochastic model


#check the Hessian matrix

#This is the simulation of data

```{r}

library('dplyr')
iter=1
Mt=50
theta<-c(0.11,1,0.03)
S0<-c(1000,1)
  
  si.out<-matrix(NA,ncol=2*iter,nrow = scale)
  #get the name
  s1.name<- paste("S1.ssa",c(1:iter),sep = ".")
  #s1.name<-rep('S1.ssa',iter) 
  s2.name<-paste("S2.ssa",c(1:iter),sep = ".")
  #s2.name<-rep('S2.ssa',iter)
  colnames(si.out) <- c(s1.name,s2.name)
  
  
 
  
 for(i in 1:iter){
  #start from here
    
    result<-na.omit(ssa.f(Mt,theta,S0)) 
    
    result[length(result[,1]),]<-c(Mt,result[length(result[,1])-1,2],result[length(result[,1])-1,3])
   
    
   S.pro<- result %>% select(c('SpeciesProtein'))
   
    ei<-rep(NA,l=length(S.pro[,1]))
    
    for(j in 2:(length(S.pro[,1])-1)){
      ei[j]<-S.pro[j,1]-S.pro[j-1,1]
    }
    
    sum.ei<- length(which(ei==1))
    
    
    
  }

   #check event
head(cbind(S.pro,ei))
tail(cbind(S.pro,ei)) 
#gain.data
index.birth<- which(ei==1)

birth.ti<-result$jump.times[index.birth]  #birth time, jumps times
  
```




$$
\begin{align*}
H_l&= \frac{2x(0)(\sum_ie_i)}{\theta_1^3\theta_2}(1-e^{-\theta_1T})-\frac{Tx(0)(\sum_ie_i)}{\theta_1^2\theta_2}(1+e^{-\theta_1T}) \\
& -\frac{T^2x(0)e^{-\theta_1T}(\sum_ie_i) }{\theta_1\theta_2} - \left(\frac{x(0)^2}{\theta_1^2}(e^{-\theta_1T}-1) \right)^2  \\
&- \frac{x(0)^2T}{\theta_1^3}e^{-\theta_1T}(e^{-\theta_1T}-1)

\end{align*}

$$


```{r}
hessian<-function(sum.ei,Mt,par1,par2,S0){
  
  the1<- par1
  the2<- par2
  
  x0<-S0[1]
  s.ei<-sum.ei
  
  
  part1<- (2*x0*s.ei*(1-exp(-the1*Mt)))/(the1^3*the2)
  
  part2<-  -(Mt*x0*s.ei*(1+exp(-the1*Mt)))/(the1^2*the2)
  
  part3<- -(Mt^2*x0*exp(-the1*Mt)*s.ei)/(the1*the2)
  
  part4<- -(x0^2*(exp(-the1*Mt)-1))^2/(the1^4)
  
  part5<- -(Mt*x0^2*exp(-the1*Mt)*(exp(-the1*Mt)-1))/(the1^3)
  
   
  local.hessian<-part1+part2 + part3+part4+  part5
  
  
  
  return(local.hessian)
}

par<-c(0.11,1)
#S0<-c(1,0)
```


The loglikelihood function for
for $\theta_1 \neq 0$,
$$
\begin{align*}
l & = \sum_{i=1}^k \left(  e_i (\ln{\theta_2}-\theta_1 t_i) + (1-e_i)\ln{\theta_3} \right) + \frac{\theta_2x_1(0)}{\theta_1} (e^{-\theta_1 T}-1) - \theta_3 I_2 + \text{C}
\end{align*}

$$

#loglikelihood

```{r}
#we need ti,ei,T

#This need to change if data change
sum.ei
birth.ti 

loglikelihood.full.data<-function(par1,par2){
   
  the1<- par1
  
  the2<- par2
  ln2<-log(the2)
  
  x0<-S0[1]
  
 
  
 out<- sum.ei*ln2-the1*sum(birth.ti)+(the2*x0*(exp(-the1*Mt)-1))/the1
 #out<100*out
  return(out)
}
```





#3D plot for Hessian

```{r}
x <- seq(0.0001, 0.13, length = 1000) #theta1
y <- seq(0.01, 2, length = 1000) #theta2

df <- expand.grid(x = x, y = y)

df<-df%>% mutate(z =hessian(sum.ei=sum.ei,Mt=50,par1=df$x,par2=df$y,S0=S0) )
# Basic contour plot


library(plot3Drgl)

plot3d(x = df$x, y = df$y, z = df$z,shade = 0.4,border = NA,xlab='theta2',ylab='theta1',zlab='hessian',col="lightblue")

 # true.par<-c(0.11,1)
  
```



#another 3D plot

```{r}
hessian.par<-function(x,y){
  
 
  the1<- x
  the2<- y
  
  x0<-S0[1]
  s.ei<-sum.ei
  
  
  part1<- (2*x0*s.ei*(1-exp(-the1*Mt)))/(the1^3*the2)
  
  part2<-  -(Mt*x0*s.ei*(1+exp(-the1*Mt)))/(the1^2*the2)
  
  part3<- -(Mt^2*x0*exp(-the1*Mt)*s.ei)/(the1*the2)
  
  part4<- -(x0^2*(exp(-the1*Mt)-1))^2/(the1^4)
  
  part5<- -(Mt*x0^2*exp(-the1*Mt)*(exp(-the1*Mt)-1))/(the1^3)
  
   
  local.hessian<-part1+part2 + part3+part4+  part5
  
  
  
  return(local.hessian)
}

```

```{r}

x <- seq(0.0005, 0.15, length = 1000) #theta1=0.11
y <- seq(0.5, 1.1, length = 1000) #theta2=1
z <- outer(x, y, hessian.par)

# plot the 3D surface
persp3d(x, y, z,col = "lightgreen", shade = 0.4)
```


#3D plot for contour for loglikelihood

```{r}


x = seq(0.1,2,l=100) #theta2
y = seq(0.09,0.15,l=100) #theta1

df <- expand.grid(x = x, y = y)

df<-df%>% mutate(z = 100*loglikelihood.full.data(par1=x,par2 = y) )
# Basic contour plot

plot3d(x = df$x, y = df$y, z = df$z,shade = 0.4,border = NA,col = "blue",xlab=expression(theta[2]),ylab=expression(theta[1]),zlab='loglikelihood')




```


#start form here


```{r}
library(plot3D)
x <- seq(0.000001, 0.15, length = 1000) #theta1
y <- seq(0.05, 100, length = 1000) #theta2
z <- outer(x, y, loglikelihood.full.data)


 t.l<-loglikelihood.full.data(par1=0.11,par2=1)
 
# xlab=expression(theta[2]),ylab=expression(theta[1]) 
 
# plot the 3D surface
persp3d(x, y, z,col = "lightblue", shade = 0,border = NA,theta = 90,xlab='theta1',ylab='theta2',zlab='loglikelihood',box = FALSE)


```


```{r}
rgl.postscript('3d-lightblue-loglikelihood.jpg', fmt = 'jpg')


+points3D(0.11, 1,t.l , col = "red", size = 60, add=T)

save

```





 
 


#contour plot

```{r} 
  basic<-ggplot(df, aes(x = x, y = y, z = z)) +   theme_minimal()
  basic+geom_density_2d()
  basic+geom_contour(bins=10)
  
  +
   geom_contour(colour="blue", size=0.2) +
  labs(title = "Contour Plot with Hessian Matrix", x = "theta1", y = "theta2")

+geom_point(x=true.par[1], y=true.par[2], colour="red")

  
```








```{r}
#non-increase data
library(akima)
im <- with(df,interp(x,y,z))
with(im,image(x,y,z))


```



```{r}
par<-c(0.11,1)
S0<-c(1,0)
```



```{r}

x <- seq(0.000001, 0.15, length = 1000) #theta1
y <- seq(0.05, 100, length = 1000) #theta2
z <- outer(x, y, hessian.par)

# plot the 3D surface
persp3d(x, y, z,col = "lightgreen", shade = 0.4)

,border = NA,theta = 90)

```









waste

```{r}
x = seq(0.001,2,l=100) #theta2
y = seq(0.001,0.1,l=100) #theta1

expand.grid(c(x),c(y))



z<- hessian(sum.ei=sum.ei,Mt=1,par1=x,par2=y,S0=S0) %>% as.data.frame()

library(rgl)

persp3d(x, y, z, col="skyblue")


```





#waste


```{r}
ssa.out.jumps.data<-function(Mt,scale,theta,S0,iter){
  
  times= matrix(NA,nrow=scale,ncol=iter)

  
  si.out<-matrix(NA,ncol=2*iter,nrow = scale)
  
  
  #get the name
  s1.name<- paste("S1.ssa",c(1:iter),sep = ".")
  #s1.name<-rep('S1.ssa',iter) 
  s2.name<-paste("S2.ssa",c(1:iter),sep = ".")
  #s2.name<-rep('S2.ssa',iter)
  colnames(si.out) <- c(s1.name,s2.name)
  
  for(i in 1:iter){
    
    result<-na.omit(ssa.f(Mt,theta,S0)) 
    result[length(result[,1]),]<-c(Mt,result[length(result[,1])-1,2],result[length(result[,1])-1,3])
   
    
   S.pro<- result %>% select(c('SpeciesProtein'))
   
    ei<-rep(NA,l=length(S.pro[,1]))
    
    for(j in 1:(length(S.pro[,1])-1)){
      ei[j]<-S.pro[j+1,1]-S.pro[j,1]
    }
    
    sum.ei<- sum(ei)
    
    
    si.out[,i]<-result[,2]
    si.out[,i+iter]<-result[,3]
    times[,i]<-result[,1]
    
  }
  
list(species=si.out,jump.times<-times)

}

```

```{r}
ssa.out.jumps.data(Mt=1,scale=100,theta=c(0.11,1,0.03),S0=c(1000,0),iter=1)
```


